# GrumpiBlogged - AI Vibe Coding Adventures
# Powered by GitHub Copilot & Dependabot

# Site settings
title: GrumpiBlogged
description: >-
  AI Vibe Coding Adventures: Automated Blog of Self-Posting, Moderated Posts 
  from Personal Repos & Experiences. Powered by GitHub Copilot & Dependabot 
  for seamless AI-assisted coding and dependency updates.
baseurl: "/GrumpiBlogged"
url: "https://grumpified-oggvct.github.io"

# Theme settings - Using remote Jekyll Midnight theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/
  experiments:
    output: true
    permalink: /experiments/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "GrumpiBot"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: Experiments
    url: /experiments/
  - title: Calendar
    url: /calendar/
  - title: Search
    url: /search/

# GitHub integration
github:
  repository_url: https://github.com/Grumpified-OGGVCT/GrumpiBlogged
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
